- hosts: cluster
  remote_user: root
  name: "Running cluster playbook"

  tasks:

  - name: Check if openshift-ansible file exists
    stat:
      path: /root/release-3.11.zip
    register: stat_result

  - name: Download openshift-ansible 3.11
    shell: wget https://github.com/openshift/openshift-ansible/archive/release-3.11.zip
    when: stat_result.stat.exists == False

  #- name: Download ansible-2.8.5-1.el7.noarch.rpm
  #  shell: wget https://rpmfind.net/linux/epel/7/x86_64/Packages/a/ansible-2.8.5-1.el7.noarch.rpm

  - name: Install EPEL repo
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present


  - name: Install ansible
    shell: yum install -y ansible

  #- name: Copy inventory template to /etc/ansible/hosts
  #  shell: cat templates/openshift_inventory_file.template > /etc/ansible/hosts

  - name: Copy Template Inventory file to /etc/ansible/hosts on cluster server
    copy:
      src: ../templates/openshift_inventory_file.template
      dest: /etc/ansible/hosts
      owner: root
      group: root
      mode: 0644

  - name: Unzip openshift-ansible 3.11 at /root
    shell: unzip release-3.11.zip
    when: stat_result.stat.exists == False

  - name: Adjust file /root/openshift-ansible-release-3.11/roles/calico/tasks/certs.yml
    shell: sed -i 's/  become/  \#become/' /root/openshift-ansible-release-3.11/roles/calico/tasks/certs.yml

  - name: Generate SSH Keys
    openssh_keypair:
      path: /root/.ssh/id_rsa
      size: 2048
      force: true

  - name: Get SSH Key from Cluster to share between hosts
    shell: cat /root/.ssh/id_rsa.pub
    register: id_rsa_cluster
  - set_fact: id_rsa_cluster_var="{{ id_rsa_cluster.stdout }}"
  
  #- debug:
  #    msg: "{{ id_rsa_cluster_var }}"

  - debug:
      msg:
      - "OpenShift packages required by the Cluster Server are now installed."
      - "You may run the prerequisites file and then the deploy cluster file:"
      - "From inside the cluster server:"
      - "  ansible-playbook -i /etc/ansible/hosts /root/openshift-ansible-release-3.11/playbooks/prerequisites.yml"
      - "  ansible-playbook -i /etc/ansible/hosts /root/openshift-ansible-release-3.11/playbooks/deploy_cluster.yml"


- hosts: all
  remote_user: root
  name: Configure each host to receive id_rsa.pub key from cluster server to all servers defined in the inventory file

  tasks:

  - name: test echo id_rsa_cluster_var
    debug:
      msg: "{{ hostvars['okd-cluster.home.net']['id_rsa_cluster_var'] }}"
    register: id_rsa_cluster_value

  - name: Configure authorized keys for cluster and node servers
    shell:
      cmd: |
        echo "{{ hostvars['okd-cluster.home.net']['id_rsa_cluster_var'] }}" >> /root/.ssh/authorized_keys

  #- name: Fetch id rsa key generated at cluster server
  #  fetch:
  #    src: /root/.ssh/id_rsa.pub
  #    dest: /tmp/tempid_rsa.pub
  #    flat: yes

#- hosts: cluster
#  remote_user: root

#  tasks:

#  - name: Fetch temp file to dest servers
#    fetch:
#      src: /tmp/tempid_rsa.pub
#      dest: /root/.ssh/tempid_rsa.pub
#      flat: yes

#  - name: Copy public key to authorized keys on each host
#    shell: cat /root/.ssh/tempid_rsa.pub >> /root/.ssh/authorized_keys
